name: petase_zero_shot
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - biopython==1.86
      - fair-esm==2.0.0
      - numpy==2.1.2
      - pandas==2.3.3
      - scipy==1.15.3
      - pillow==11.3.0
      - networkx==3.3
      - sympy==1.14.0
